/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package servicioescolar.util;

import java.util.Arrays;
import java.util.List;

/**
 *
 * @author Bulbtic
 */
public class AlumnoUtil {

    public static List<String>  NOMBRES = Arrays.asList("SANTIAGO",
            "EDUARDO",
            "VICTOR",
            "MARIO",
            "ROBERTO",
            "JAIME",
            "FRANCISCO JOSE",
            "IGNACIO",
            "MARCOS",
            "ALFONSO",
            "JORDI",
            "SALVADOR",
            "RICARDO",
            "EMILIO",
            "HUGO",
            "GUILLERMO",
            "GABRIEL",
            "JULIAN",
            "JULIO",
            "MARC",
            "TOMAS",
            "JOSE MIGUEL",
            "GONZALO",
            "AGUSTIN",
            "MOHAMED",
            "JOSE RAMON",
            "FELIX",
            "NICOLAS",
            "JOAN",
            "MARTIN",
            "ISMAEL",
            "CRISTIAN",
            "SAMUEL",
            "AITOR",
            "JUAN FRANCISCO",
            "JOSEP",
            "HECTOR",
            "MARIANO",
            "DOMINGO",
            "JOSE CARLOS",
            "ALFREDO",
            "SEBASTIAN",
            "IKER",
            "CESAR",
            "FELIPE",
            "ALEX",
            "LUCAS",
            "JOSE ANGEL",
            "JOSE IGNACIO",
            "VICTOR MANUEL",
            "LUIS MIGUEL",
            "RODRIGO",
            "GREGORIO",
            "JOSE FRANCISCO",
            "JUAN LUIS",
            "XAVIER",
            "ALBERT",
            "MARIA CARMEN",
            "MARIA",
            "CARMEN",
            "JOSEFA",
            "ANA MARIA",
            "ISABEL",
            "MARIA PILAR",
            "MARIA DOLORES",
            "LAURA",
            "MARIA TERESA",
            "ANA",
            "CRISTINA",
            "MARIA ANGELES",
            "MARTA",
            "FRANCISCA",
            "ANTONIA",
            "MARIA ISABEL",
            "MARIA JOSE",
            "DOLORES",
            "LUCIA",
            "SARA",
            "PAULA",
            "MARIA LUISA",
            "ELENA",
            "PILAR",
            "CONCEPCION",
            "RAQUEL",
            "ROSA MARIA",
            "MANUELA",
            "MERCEDES",
            "MARIA JESUS",
            "ROSARIO",
            "BEATRIZ",
            "JUANA",
            "TERESA",
            "JULIA",
            "NURIA",
            "SILVIA",
            "ENCARNACION",
            "IRENE",
            "ALBA",
            "PATRICIA",
            "MONTSERRAT",
            "ANDREA",
            "ROSA",
            "ROCIO",
            "MONICA",
            "MARIA MAR",
            "ALICIA",
            "ANGELA",
            "SONIA",
            "SANDRA",
            "MARINA",
            "SUSANA",
            "YOLANDA",
            "NATALIA",
            "MARGARITA",
            "MARIA JOSEFA",
            "MARIA ROSARIO",
            "EVA",
            "INMACULADA",
            "CLAUDIA",
            "MARIA MERCEDES",
            "ANA ISABEL",
            "ESTHER",
            "NOELIA",
            "CARLA",
            "VERONICA",
            "SOFIA",
            "ANGELES",
            "CAROLINA",
            "NEREA",
            "MARIA VICTORIA",
            "MARIA ROSA",
            "EVA MARIA",
            "AMPARO",
            "MIRIAM",
            "LORENA",
            "INES",
            "MARIA CONCEPCION",
            "ANA BELEN",
            "MARIA ELENA",
            "VICTORIA",
            "MARIA ANTONIA",
            "DANIELA",
            "CATALINA",
            "CONSUELO",
            "LIDIA",
            "MARIA NIEVES",
            "CELIA",
            "ALEJANDRA",
            "OLGA",
            "EMILIA",
            "GLORIA",
            "LUISA",
            "AINHOA",
            "AURORA",
            "MARIA SOLEDAD",
            "MARTINA",
            "FATIMAMARIA PILAR",
            "MARIA",
            "MARIA CARMEN",
            "CARMEN",
            "PILAR",
            "MARIA TERESA",
            "ANA MARIA",
            "LAURA",
            "ANA",
            "MARIA JOSE",
            "JOSEFA",
            "MARIA JESUS",
            "MARIA ISABEL",
            "MARIA ANGELES",
            "MARTA",
            "CRISTINA",
            "ELENA",
            "ISABEL",
            "MARIA DOLORES",
            "LUCIA",
            "CONCEPCION",
            "SARA",
            "MARIA LUISA",
            "ROSA MARIA",
            "TERESA",
            "MERCEDES",
            "SILVIA",
            "JULIA",
            "RAQUEL",
            "PAULA",
            "FRANCISCA",
            "BEATRIZ",
            "MONTSERRAT",
            "JOSEFINA",
            "ANTONIA",
            "ALBA",
            "ALICIA",
            "IRENE",
            "ANDREA",
            "PATRICIA",
            "ANA ISABEL",
            "ANGELES",
            "ESTHER",
            "NURIA",
            "ROSARIO",
            "YOLANDA",
            "ROSA");
    public static List<String> PRIMEROS_APELLIDOS = Arrays.asList("GARCIA",
            "GONZALEZ",
            "RODRIGUEZ",
            "FERNANDEZ",
            "LOPEZ",
            "MARTINEZ",
            "SANCHEZ",
            "PEREZ",
            "GOMEZ",
            "MARTIN",
            "JIMENEZ",
            "RUIZ",
            "HERNANDEZ",
            "DIAZ",
            "MORENO",
            "MUÑOZ",
            "ALVAREZ",
            "ROMERO",
            "ALONSO",
            "GUTIERREZ",
            "NAVARRO",
            "TORRES",
            "DOMINGUEZ",
            "VAZQUEZ",
            "RAMOS",
            "GIL",
            "RAMIREZ",
            "SERRANO",
            "BLANCO",
            "MOLINA",
            "MORALES",
            "SUAREZ",
            "ORTEGA",
            "DELGADO",
            "CASTRO",
            "ORTIZ",
            "RUBIO",
            "MARIN",
            "SANZ",
            "NUÑEZ",
            "IGLESIAS",
            "MEDINA",
            "GARRIDO",
            "CORTES",
            "CASTILLO",
            "SANTOS",
            "LOZANO",
            "GUERRERO",
            "CANO",
            "PRIETO",
            "MENDEZ",
            "CRUZ",
            "CALVO",
            "GALLEGO",
            "HERRERA",
            "MARQUEZ",
            "LEON",
            "VIDAL",
            "PEÑA",
            "FLORES",
            "CABRERA",
            "CAMPOS",
            "VEGA",
            "FUENTES",
            "CARRASCO",
            "DIEZ",
            "REYES",
            "CABALLERO",
            "NIETO",
            "AGUILAR",
            "PASCUAL",
            "SANTANA",
            "HERRERO",
            "MONTERO",
            "LORENZO",
            "HIDALGO",
            "GIMENEZ",
            "IBAÑEZ",
            "FERRER",
            "DURAN",
            "SANTIAGO",
            "BENITEZ",
            "VARGAS",
            "MORA",
            "VICENTE",
            "ARIAS",
            "CARMONA",
            "CRESPO",
            "ROMAN",
            "PASTOR",
            "SOTO",
            "SAEZ",
            "VELASCO",
            "MOYA",
            "SOLER",
            "PARRA",
            "ESTEBAN",
            "BRAVO",
            "GALLARDO",
            "ROJAS",
            "GARCIA",
            "MARTINEZ",
            "PEREZ",
            "SANCHEZ",
            "LOPEZ",
            "RODRIGUEZ",
            "FERNANDEZ",
            "GONZALEZ",
            "GOMEZ",
            "NAVARRO",
            "RUIZ",
            "HERNANDEZ",
            "MORENO",
            "PASTOR",
            "MUÑOZ",
            "JIMENEZ",
            "DIAZ",
            "TORRES",
            "MOLINA",
            "GIL",
            "MARTIN",
            "ROMERO",
            "SERRANO",
            "SOLER",
            "RICO",
            "CORTES",
            "MAS",
            "JUAN",
            "VALERO",
            "GIMENEZ",
            "MARIN",
            "PASCUAL",
            "RUBIO",
            "MIRA",
            "VERDU",
            "FERRER",
            "BERNABEU",
            "SEMPERE",
            "VIDAL",
            "ALVAREZ",
            "ORTIZ",
            "ANTON",
            "GUTIERREZ",
            "AMOROS",
            "MIRALLES",
            "RAMIREZ",
            "SAEZ",
            "ORTEGA",
            "ALONSO",
            "SORIANO",
            "GARCIA",
            "MARTINEZ",
            "PEREZ",
            "LOPEZ",
            "SANCHEZ",
            "GRACIA",
            "GONZALEZ",
            "HERNANDEZ",
            "GOMEZ",
            "MARTIN",
            "FERNANDEZ",
            "RODRIGUEZ",
            "JIMENEZ",
            "RUIZ",
            "GIL",
            "NAVARRO",
            "SANZ",
            "SERRANO",
            "MORENO",
            "GIMENEZ",
            "MUÑOZ",
            "GIMENO",
            "MARIN",
            "BLASCO",
            "CALVO",
            "MARCO",
            "ALONSO",
            "ROYO",
            "SANCHO",
            "IBAÑEZ",
            "LAZARO",
            "RUBIO",
            "VICENTE",
            "AZNAR",
            "ALVAREZ",
            "DIAZ",
            "CORTES",
            "ESTEBAN",
            "ROMERO",
            "ANDRES",
            "GUTIERREZ",
            "TORRES",
            "DOMINGUEZ",
            "FERRER",
            "RAMOS",
            "RODRIGO",
            "FRANCO",
            "CASTILLO",
            "SIERRA",
            "PASCUAL");

    public static List<String> SEGUNDOS_APELLIDOS = Arrays.asList("FERNANDEZ",
            "RODRIGUEZ",
            "GARCIA",
            "MARTIN",
            "GONZALEZ",
            "PEREZ",
            "ALONSO",
            "HERNANDEZ",
            "SANCHEZ",
            "LOPEZ",
            "MARTINEZ",
            "ALVAREZ",
            "PRIETO",
            "DOMINGUEZ",
            "BLANCO",
            "RAMOS",
            "GOMEZ",
            "FERRERO",
            "CALVO",
            "LORENZO",
            "GALLEGO",
            "VICENTE",
            "ESTEBAN",
            "JIMENEZ",
            "VEGA",
            "GUTIERREZ",
            "SANTOS",
            "CRESPO",
            "MATEOS",
            "DIEZ",
            "HERRERO",
            "MIGUEL",
            "GAGO",
            "VARA",
            "VILLAR",
            "ANDRES",
            "IGLESIAS",
            "PASCUAL",
            "VAQUERO",
            "SANTIAGO",
            "NIETO",
            "CASADO",
            "DELGADO",
            "LOZANO",
            "ROMAN",
            "MARCOS",
            "ANTON",
            "MORAN",
            "ROMERO",
            "VAZQUEZGARCIA",
            "FERNANDEZ",
            "GONZALEZ",
            "RODRIGUEZ",
            "LOPEZ",
            "PEREZ",
            "MARTINEZ",
            "SANCHEZ",
            "MARTIN",
            "GOMEZ",
            "RUIZ",
            "ALONSO",
            "BILBAO",
            "ALVAREZ",
            "GUTIERREZ",
            "HERNANDEZ",
            "DIEZ",
            "JIMENEZ",
            "DIAZ",
            "VAZQUEZ",
            "MUÑOZ",
            "BLANCO",
            "MORENO",
            "URIARTE",
            "ORTEGA",
            "PEÑA",
            "AGUIRRE",
            "IGLESIAS",
            "ORTIZ",
            "DOMINGUEZ",
            "GIL",
            "ZABALA",
            "RAMOS",
            "SANTOS",
            "ROMERO",
            "SANTAMARIA",
            "CALVO",
            "PRIETO",
            "DELGADO",
            "NUÑEZ",
            "ETXEBARRIA",
            "ECHEVARRIA",
            "SANZ",
            "CASTRO",
            "HERRERO",
            "MENDEZ",
            "MERINO",
            "TORRES",
            "MARCOS",
            "IBAÑEZGARCIA",
            "MARTINEZ",
            "LOPEZ",
            "PEREZ",
            "SANCHEZ",
            "GONZALEZ",
            "GOMEZ",
            "NAVARRO",
            "FERNANDEZ",
            "RODRIGUEZ",
            "MORENO",
            "RUIZ",
            "MUÑOZ",
            "HERNANDEZ",
            "ROMERO",
            "JIMENEZ",
            "FERRER",
            "SANCHIS",
            "TORRES",
            "MARTI",
            "GIMENEZ",
            "GIL",
            "DIAZ",
            "MARTIN",
            "SOLER",
            "RUBIO",
            "SERRANO",
            "SANZ",
            "VIDAL",
            "SORIANO",
            "ORTIZ",
            "MOLINA",
            "GIMENO",
            "PASTOR",
            "IBAÑEZ",
            "RAMIREZ",
            "MARIN",
            "ALVAREZ",
            "SAEZ",
            "BLASCO",
            "CORTES",
            "PERIS",
            "PARDO",
            "ORTEGA",
            "VALERO",
            "PASCUAL",
            "GARRIDO",
            "CERVERA",
            "JUAN",
            "ALONSOGARCIA",
            "SANCHEZ",
            "FERNANDEZ",
            "MARTIN",
            "RODRIGUEZ",
            "LOPEZ",
            "GOMEZ",
            "GONZALEZ",
            "PEREZ",
            "DIAZ",
            "JIMENEZ",
            "MORENO",
            "MUÑOZ",
            "MARTINEZ",
            "HERNANDEZ",
            "GUTIERREZ",
            "RUIZ",
            "ALONSO",
            "SERRANO",
            "ROMERO",
            "ALVAREZ",
            "TORRES",
            "RAMOS",
            "RAMIREZ",
            "RUBIO",
            "ORTIZ",
            "MORA",
            "MORALES",
            "GALAN",
            "CANO",
            "NAVARRO",
            "VAZQUEZ",
            "ORTEGA",
            "GALLEGO",
            "GARRIDO",
            "NUÑEZ",
            "DOMINGUEZ",
            "NIETO",
            "MOLINA",
            "SANTOS",
            "DE LA CRUZ",
            "BLANCO",
            "DELGADO",
            "MEDINA",
            "ESTEBAN",
            "AGUADO",
            "REDONDO",
            "GIL",
            "ROJAS",
            "CARRASCO",
            "HERNANDEZ",
            "PASTOR",
            "MORENO");
}
